import { ImageResponse } from '@vercel/og'
import { createAdminClient } from '@/utils/supabase/admin'

export const runtime = 'edge'

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url)
    const sessionId = searchParams.get('session_id')
    const hosterId = searchParams.get('hoster_id')

    const supabase = createAdminClient()

    if (sessionId) {
      const { data: session } = await supabase
        .from('sessions')
        .select('summary_data, created_at')
        .eq('id', sessionId)
        .single()

      if (!session || !session.summary_data) {
        return new Response('Session summary not found', { status: 404 })
      }

      const { mvp, leaderboard } = session.summary_data
      const date = new Date(session.created_at).toLocaleDateString()
      const biggestGainer = [...leaderboard].sort((a: any, b: any) => b.mmrChange - a.mmrChange)[0]

      return new ImageResponse(
        (
          <div
            style={{
              height: '100%',
              width: '100%',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              backgroundColor: '#030712', // gray-950
              fontFamily: 'sans-serif',
              color: 'white',
              padding: '60px',
            }}
          >
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                marginBottom: '40px',
              }}
            >
              <div style={{ fontSize: 60, fontWeight: 900, marginRight: 20 }}>VolleyMatch</div>
            </div>

            <div
              style={{
                display: 'flex',
                flexDirection: 'column',
                backgroundColor: '#111827', // gray-900
                padding: '40px',
                borderRadius: '24px',
                width: '100%',
                border: '2px solid #1F2937', // gray-800
              }}
            >
              <div style={{ fontSize: 40, fontWeight: 800, marginBottom: '10px', color: '#F9FAFB' }}>
                Game Day Recap
              </div>
              <div style={{ fontSize: 24, color: '#9CA3AF', marginBottom: '40px' }}>
                {date}
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', width: '100%' }}>
                {/* MVP */}
                {mvp && (
                  <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
                    <div style={{ fontSize: 24, color: '#FBBF24', fontWeight: 700, marginBottom: '10px' }}>
                      MVP
                    </div>
                    <div style={{ fontSize: 48, fontWeight: 800 }}>{mvp.name}</div>
                    <div style={{ fontSize: 24, color: '#9CA3AF' }}>{mvp.games_played} Games</div>
                  </div>
                )}

                {/* Biggest Gainer */}
                {biggestGainer && biggestGainer.mmrChange > 0 && (
                  <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
                    <div style={{ fontSize: 24, color: '#34D399', fontWeight: 700, marginBottom: '10px' }}>
                      Biggest Gainer
                    </div>
                    <div style={{ fontSize: 48, fontWeight: 800 }}>{biggestGainer.name}</div>
                    <div style={{ fontSize: 24, color: '#34D399' }}>+{biggestGainer.mmrChange} MMR</div>
                  </div>
                )}
              </div>
            </div>
            
            <div style={{ display: 'flex', marginTop: '40px', fontSize: 24, color: '#6B7280' }}>
              Generated by VolleyMatch
            </div>
          </div>
        ),
        {
          width: 1200,
          height: 630,
        }
      )
    }

    if (hosterId) {
      // Placeholder for Hoster stats OG image
      return new ImageResponse(
        (
          <div
            style={{
              height: '100%',
              width: '100%',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              backgroundColor: '#030712',
              color: 'white',
            }}
          >
            <div style={{ fontSize: 60, fontWeight: 900 }}>VolleyMatch</div>
            <div style={{ fontSize: 40, marginTop: 20, color: '#9CA3AF' }}>Host Stats Summary</div>
          </div>
        ),
        { width: 1200, height: 630 }
      )
    }

    return new Response('Missing session_id or hoster_id', { status: 400 })
  } catch (e: any) {
    console.error(e)
    return new Response(`Failed to generate image: ${e.message}`, { status: 500 })
  }
}
